routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AppointmentsController;



Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/registration', [RegisterController::class, 'index'])->name('register');
Route::post('/registration', [RegisterController::class, 'register'])->name('register');

Route::resource('appointments', AppointmentsController::class)->middleware('auth');

app/Models/Appointment.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Reminder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Appointment extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'description',
        'start_time',
        'end_time'
    ];

    protected $casts = ['start_time' => 'datetime', 'end_time' => 'datetime'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function reminder(): HasOne
    {
        return $this->hasOne(Reminder::class);
    }
}

app/Models/Reminder.php
<?php

namespace App\Models;

use App\Models\Appointment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Reminder extends Model
{
    use HasFactory;

    protected $fillable = [
        'appointment_id',
        'days_before',
        'job_id'
    ];

    public function appointments()
    {
        return $this->belongsTo(Appointment::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Models\Appointment;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    public function appointments(): HasMany
    {
        return $this->hasMany(Appointment::class);
    }

  
}

app/Http/Controllers/AppointmentsController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\View\View;
use App\Mail\ReminderEmail;
use App\Models\Appointment;
use Illuminate\Http\Request;
use App\Jobs\DeleteAppointmentJob;
use App\Jobs\SendReminderEmailJob;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewAppointmentInfoEmail;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Queue;

class AppointmentsController extends Controller
{
    public function index(): View
    {
        $user = auth()->user();
        $appointments = $user->appointments;

        return view('appointments', compact('user', 'appointments'));
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'title' => 'required|string',
            'description' => 'string',
            'start-time' => 'required|date',
            'end-time' => 'required|date|after:start-time',
            'reminder' => 'required|integer'
        ]);

        $user = auth()->user();

        $appointment = $user->appointments()->create([
            'title' => $request->title,
            'description' => $request->description,
            'start_time' => ($request->input('start-time')),
            'end_time' => ($request->input('end-time')),
        ]);


        $reminder = $appointment->reminder()->create([
            'days_before' => $request->input('reminder'),
        ]);

        $reminderDateTime = $appointment->start_time->subDays($reminder->days_before);

        Mail::to($user->email)->send(new NewAppointmentInfoEmail($appointment->title, $user->name, $reminderDateTime));

        Mail::to($user->email)->later($reminderDateTime, new ReminderEmail($appointment->title, $reminder->days_before));

        return redirect()->route('appointments.index')->with('success', 'Appointment added successfully');
    }

    public function destroy(string $id): RedirectResponse
    {
        $appointment = Appointment::findOrFail($id);

        if ($appointment->reminder) {
            $appointment->reminder->delete();
        }

        $appointment->delete();

        return back()->with('success', 'deleted successfully');
    }

    public function show(string $id): View
    {
        return view('show-appointment', [
            'appointment' => Appointment::findOrFail($id)
        ]);
    }

    public function update(Request $request, string $id): RedirectResponse
    {
        $appointment = Appointment::findOrFail($id);

        $request->validate([
            'title' => 'required|string',
            'description' => 'string',
            'start-time' => 'required|date',
            'end-time' => 'required|date|after:start-time',
            'reminder' => 'required|integer'
        ]);

        $appointment->update([
            'title' => $request->title,
            'description' => $request->description,
            'start_time' => ($request->input('start-time')),
            'end_time' => ($request->input('end-time')),
        ]);

        $appointment->reminder->update([
            'days_before' => $request->input('reminder'),
        ]);

        return redirect()->route('appointments.index')->with('success', 'appointment updated successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;

class HomeController extends Controller
{
    public function index(): View
    {
        return view('home');
    }
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;

class LoginController extends Controller
{
    public function index(): View
    {
        return view("login");
    }

    public function login(Request $request): RedirectResponse
    {
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            return redirect()->route('appointments.index')->with('success', 'login successful');
        }

        return back()->withErrors(['email' => 'Invalid email or password'])->withInput();
    }
    public function logout(): RedirectResponse
    {
        Auth::logout();
        return redirect()->route('home')->with('success', 'logout successful');
    }
}

app/Http/Controllers/RegisterController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\View\View;
use App\Mail\ReminderEmail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\RedirectResponse;

class RegisterController extends Controller
{
    public function index(): View
    {
        return view('registration');
    }

    public function register(Request $request): RedirectResponse
    {
        $request->validate([
            'name' => 'required|string|min:3|max:55',
            'email' => 'required|string|unique:users|max:255',
            'password' => 'required|string|min:8|confirmed',
            'terms' => 'required|accepted'
        ]);

        User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password'))
        ]);
       
        return redirect()->route('home')->with('success', 'Registration successful! , please login');
    }
}

resources/views/appointments.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <h2 class="mt-4">Hi, {{ $user->name }}!</h2>
        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add new appointment
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add new appointment</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{ route('appointments.store') }}" id="appointment-form">
                            @csrf
                            <div class="mb-3">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" class="form-control" id="title" name="title" required
                                    value={{ old('title') }}>
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea name="description" class="form-control" id="description" cols="30" rows="5" required>{{ old('description') }}</textarea>
                                @error('description')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="start-time" class="form-label">Start Time</label>
                                <input type="datetime-local" name="start-time" class="form-control" id="start-time"
                                    required>
                                @error('start-time')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="end-time" class="form-label">End Time</label>
                                <input type="datetime-local" name="end-time" class="form-control" id="end-time" required>
                                @error('end-time')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="reminder" class="form-label">Reminder</label>
                                <select name="reminder" class="form-select" id="reminder" required>
                                    <option value="1">Remind 1 day before</option>
                                    <option value="2">Remind 2 days before</option>
                                    <option value="7">Remind 1 week before</option>
                                </select>
                                @error('reminder')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                    </div>
                    <div class="modal-footer">
                        <div id="loading-message" style="display: none;">Creating appointment...</div>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="submit-btn">Add new appointment</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>

        @if ($appointments->isEmpty())
            <p>No appointments available.</p>
        @else
            <table class="table mt-4">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Start Time</th>
                        <th scope="col">End Time</th>
                        <th scope="col">Reminder</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($appointments as $appointment)
                        <tr>
                            <th scope="row">{{ $loop->index + 1 }}</th>
                            <td>
                                <a href={{ route('appointments.show', $appointment->id) }}
                                    class="text-decoration-none text-primary fw-bold">
                                    {{ $appointment->title }}
                                </a>
                            </td>
                            <td>{{ $appointment->description }}</td>
                            <td>{{ $appointment->start_time }}</td>
                            <td>{{ $appointment->end_time }}</td>
                            <td>{{ $appointment->reminder->days_before }} days before</td>
                            <td>
                                <form method="POST" action="{{ route('appointments.destroy', $appointment->id) }}"
                                    class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger btn-block">
                                        <i class="bi bi-trash"></i> Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
        @endif

    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.main')


@section('content')
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-12 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Vertically centered hero sign-up form
            </h1>
            <p class="col-lg-10 fs-4">Below is an example form built entirely with Bootstrap’s form controls.
                Each required form group has a validation state that can be triggered by attempting to submit
                the form without completing it.</p>
        </div>
    </div>
@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Reminder App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
    @vite('resources/js/app.js')

</head>

<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/"
                class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <svg class="bi me-2" width="40" height="32">
                    <use xlink:href="#bootstrap"></use>
                </svg>
                <span class="fs-4">Your Reminder App</span>
            </a>
            @guest
                <ul class="nav nav-pills">
                    <li class="nav-item"><a href={{ route('login') }} class="nav-link active" aria-current="page">Login</a>
                    </li>
                </ul>
            @endguest

            @auth
                <ul class="nav nav-pills">
                    <li class="nav-item"><a href={{ route('appointments.index') }} class="nav-link active"
                            aria-current="page">My Appointments</a></li>

                    <li class="nav-item">
                        <form method='post' action={{ route('logout') }}>
                            @csrf
                            <button class="nav-link" type="submit">Logout</button>
                        </form>
                    </li>
                </ul>
            @endauth

        </header>
        <div class="container col-xl-10 col-xxl-8 px-4 py-5">
            @yield('content')
        </div>
    </div>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24"
                        height="24">
                        <use xlink:href="#twitter"></use>
                    </svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24"
                        height="24">
                        <use xlink:href="#instagram"></use>
                    </svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24"
                        height="24">
                        <use xlink:href="#facebook"></use>
                    </svg></a></li>
        </ul>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous">
    </script>
</body>

</html>

resources/views/login.blade.php
@extends('layouts.main')

@section('content')
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
            @guest
                <form method="post" action={{ route('login') }} class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                    @csrf
                    <div class="form-floating mb-3">
                        <input type="email" name='email' class="form-control" id="email" placeholder="name@example.com">
                        <label for="email">Email address</label>
                        @error('email')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name='password' class="form-control" id="password" placeholder="Password">
                        <label for="password">Password</label>
                        @error('password')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
                    <hr class="my-4">
                    New here ? <a href="{{ route('register') }}" class="btn btn-primary">Register</a>
                    <hr class="my-4">
                    <small class="text-body-secondary">By clicking Sign up, you agree to the terms of use.</small>
                </form>
            @endguest
        </div>


    </div>
@endsection

resources/views/registration.blade.php
@extends('layouts.main')

@section('content')
    <form method="post" action="{{ route('register') }}">
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="name" name="name" class="form-control" id="name" aria-describedby="emailHelp"
                value={{ old('name') }}>
            @error('name')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                value={{ old('email') }}>
            @error('email')
                <div class="text-danger">{{ $message }}</div>
            @enderror
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password">
            @error('password')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="password_confirmation" class="form-label">Confirm Password</label>
            <input type="password" name="password_confirmation" class="form-control" id="password_confirmation">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" name='terms' class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
            @error('terms')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
@endsection

resources/views/show-appointment.blade.php
@extends('layouts.main')

@section('content')
    <form method="post" action="{{ route('appointments.update', $appointment->id) }}">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $appointment->title }}" required>
            @error('title')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea name="description" class="form-control" id="description" cols="30" rows="5" required>{{ $appointment->description }}</textarea>
            @error('description')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="start-time" class="form-label">Start Time</label>
            <input type="datetime-local" name="start-time" class="form-control" id="start-time"
                value="{{ $appointment->start_time }}">
            @error('start-time')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="end-time" class="form-label">End Time</label>
            <input type="datetime-local" name="end-time" class="form-control" id="end-time"
                value="{{ $appointment->end_time }}">
            @error('end-time')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="reminder" class="form-label">Reminder</label>
            <select name="reminder" class="form-select" id="reminder" required>
                <option value="1" {{ $appointment->reminder->days_before == 1 ? 'selected' : '' }}>Remind 1 day before
                </option>
                <option value="2" {{ $appointment->reminder->days_before == 2 ? 'selected' : '' }}>Remind 2 days
                    before</option>
                <option value="7" {{ $appointment->reminder->days_before == 7 ? 'selected' : '' }}>Remind 1 week
                    before</option>
            </select>
            @error('reminder')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Edit Appointment</button>
    </form>
@endsection